# Generated by Django 5.2.7 on 2025-12-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snmpcommunity',
            options={'permissions': [('view_encrypted_data', 'Can view encrypted community fields.')]},
        ),
        migrations.AddField(
            model_name='snmpcommunity',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
